Repository jabardigitalservice/reservasi-backend, pull requests merged in 2021-02, with the labels that each got.

#34 Update phpunit development
  app/Models/Reservation.php
  config/mail.php
  phpunit.xml
  tests/Feature/AssetTest.php
  tests/Feature/ReservationTest.php
  tests/Feature/ReservedTest.php
Labels: bug

#40 fix issue mass assignment on asset
  app/Http/Controllers/V1/AssetController.php
Labels: good first issue

#45 Zoom integrate
  .env.example
  app/Enums/ResourceTypeEnum.php
  app/Events/AfterReservation.php
  app/Http/Controllers/V1/AssetController.php
  app/Http/Controllers/V1/ReservationController.php
  app/Http/Controllers/V1/ReservedController.php
  app/Http/Middleware/Authenticate.php
  app/Http/Resources/ReservationResource.php
  app/Listeners/CreateZoomMeeting.php
  app/Listeners/SendReservationEmail.php
  app/Mail/ReservationApprovalMail.php
  app/Models/Asset.php
  app/Models/Reservation.php
  app/Observers/ReservationObserver.php
  app/Providers/EventServiceProvider.php
  composer.json
  composer.lock
  config/zoom.php
  database/factories/AssetFactory.php
  database/migrations/2021_02_21_224312_add_join_url_to_reservations_table.php
  database/migrations/2021_02_22_075358_alter-table-assets-add-resource-type.php
  database/migrations/2021_02_22_093057_alter-table-assets-add-secret-key-client-key.php
  resources/views/emails/reservationApproval.blade.php
  tests/Feature/AssetTest.php
  tests/Feature/ReservationTest.php
  tests/Feature/ReservedTest.php
Labels: enhancement

#52 #39 remove abort if using Request from Laravel
  app/Http/Controllers/V1/ReservationController.php
Labels: enhancement

#53 #49 remove unneed format time if using default
  app/Models/Reservation.php
Labels: enhancement

#58 #57 adding field asset_id`
  app/Http/Resources/ReservationResource.php
Labels: enhancement

#59 add endpoint list all reservation for FE calendar
  app/Http/Controllers/V1/ReservationListAllController.php
  routes/api.php
  tests/Feature/ReservationTest.php
Labels: enhancement
